### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by re-becca** [qld-gov-au/swe#18]
Use this issue to discuss the [image component](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/images).

**Comment by jortronQGov** [comment]
Hi team, 

The image component currently has a max-width of 300px. This makes sense so the text wraps when the image is left or right aligned, but not as much sense when centre aligned. 

Could we look at adding a full width option to the component?

**Comment by re-becca** [comment]
Hi @jortronQGov, your suggestion to _add a full-width option to the (figure) image component_ is now available with the release of SWE v4.3.0. Thanks again for sharing it here.
