### ISSUE TITLE
Promotional tile

### ISSUE THREAD

**Issue by re-becca** [qld-gov-au/swe#25]
Use this issue to discuss the [promotional tile component](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/promotional-tile).

**Comment by LisaBee** [comment]
Is the border above the call to action button really necessary? I feel it's cleaner without, and doesn't require as much vertical space (since you don't need two lots of padding).

![Image](https://user-images.githubusercontent.com/9208750/228730755-0a04e739-5d9e-40d6-9fd2-4b382cfd1e5c.png)
