### ISSUE TITLE
Quick exit

### ISSUE THREAD

**Issue by re-becca** [qld-gov-au/swe#46]
Use this issue to discuss the [quick exit component](https://www.forgov.qld.gov.au/information-and-communication-technology/communication-and-publishing/website-and-digital-publishing/website-standards-guidelines-and-templates/swe/components/quick-exit).

**Comment by lakshmi-nidamarthi** [comment]
I would like to suggest on the DFV page along with Quick exit (Close this site) option, if we can also add **ESC key ** as an option to close the site when needed.  I found that it is much quicker to close the page than to scroll and look for  **close this site button.**  ESC, is one suggested ways to close the sites in the Tips to browse safely online.

**Comment by re-becca** [comment]
Thanks for your suggestion @lakshmi-nidamarthi. We made it clearer in [release 4.4.0](https://github.com/qld-gov-au/qg-web-template/releases/tag/v4.4.0) that the use of the 'ESC' key is an option for a quick exit.
